package GiftShop;


/**
* GiftShop/_giftintfImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

public abstract class _giftintfImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements GiftShop.giftintf, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _giftintfImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("check_gift", new java.lang.Integer (0));
    _methods.put ("process_gift", new java.lang.Integer (1));
    _methods.put ("total_price", new java.lang.Integer (2));
    _methods.put ("pay_bill", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GiftShop/giftintf/check_gift
       {
         String gift_id = in.read_string ();
         String $result = null;
         $result = this.check_gift (gift_id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // GiftShop/giftintf/process_gift
       {
         String gift_id = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.process_gift (gift_id, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // GiftShop/giftintf/total_price
       {
         int $result = (int)0;
         $result = this.total_price ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // GiftShop/giftintf/pay_bill
       {
         String $result = null;
         $result = this.pay_bill ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GiftShop/giftintf:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _giftintfImplBase
