package GiftShop;


/**
* GiftShop/Gift.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

public final class Gift implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int count = (int)0;
  public int price = (int)0;

  public Gift ()
  {
  } // ctor

  public Gift (String _name, int _count, int _price)
  {
    name = _name;
    count = _count;
    price = _price;
  } // ctor

} // class Gift
