package GiftShop;


/**
* GiftShop/giftintfHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

abstract public class giftintfHelper
{
  private static String  _id = "IDL:GiftShop/giftintf:1.0";

  public static void insert (org.omg.CORBA.Any a, GiftShop.giftintf that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GiftShop.giftintf extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GiftShop.giftintfHelper.id (), "giftintf");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GiftShop.giftintf read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_giftintfStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GiftShop.giftintf value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GiftShop.giftintf narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GiftShop.giftintf)
      return (GiftShop.giftintf)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GiftShop._giftintfStub stub = new GiftShop._giftintfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GiftShop.giftintf unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GiftShop.giftintf)
      return (GiftShop.giftintf)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GiftShop._giftintfStub stub = new GiftShop._giftintfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
