package GiftShop;

/**
* GiftShop/giftintfHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

public final class giftintfHolder implements org.omg.CORBA.portable.Streamable
{
  public GiftShop.giftintf value = null;

  public giftintfHolder ()
  {
  }

  public giftintfHolder (GiftShop.giftintf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GiftShop.giftintfHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GiftShop.giftintfHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GiftShop.giftintfHelper.type ();
  }

}
