package GiftShop;


/**
* GiftShop/ProductsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

abstract public class ProductsHelper
{
  private static String  _id = "IDL:GiftShop/Products:1.0";

  public static void insert (org.omg.CORBA.Any a, GiftShop.Products that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GiftShop.Products extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = GiftShop.GiftHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (10, _tcOf_members0 );
          _members0[0] = new org.omg.CORBA.StructMember (
            "gifts",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (GiftShop.ProductsHelper.id (), "Products", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GiftShop.Products read (org.omg.CORBA.portable.InputStream istream)
  {
    GiftShop.Products value = new GiftShop.Products ();
    value.gifts = new GiftShop.Gift[10];
    for (int _o0 = 0;_o0 < (10); ++_o0)
    {
      value.gifts[_o0] = GiftShop.GiftHelper.read (istream);
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GiftShop.Products value)
  {
    if (value.gifts.length != (10))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (10); ++_i0)
    {
      GiftShop.GiftHelper.write (ostream, value.gifts[_i0]);
    }
  }

}
