package GiftShop;


/**
* GiftShop/Products.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

public final class Products implements org.omg.CORBA.portable.IDLEntity
{
  public GiftShop.Gift gifts[] = null;

  public Products ()
  {
  } // ctor

  public Products (GiftShop.Gift[] _gifts)
  {
    gifts = _gifts;
  } // ctor

} // class Products
