package GiftShop;

/**
* GiftShop/ProductsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from shop.idl
* Saturday, 3 April, 2021 12:34:27 PM IST
*/

public final class ProductsHolder implements org.omg.CORBA.portable.Streamable
{
  public GiftShop.Products value = null;

  public ProductsHolder ()
  {
  }

  public ProductsHolder (GiftShop.Products initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GiftShop.ProductsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GiftShop.ProductsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GiftShop.ProductsHelper.type ();
  }

}
